using System.Globalization;

namespace HexWin.Ui;

public sealed partial class UiStrings
{
    public static readonly UiStrings English = new()
    {
        Culture = CultureInfo.GetCultureInfo("en-US"),

        SettingNames = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["modelPath"] = "Model folder",
            ["hotkey"] = "Hotkey",
            ["minRecordingMilliseconds"] = "Minimum length",
            ["maxRecordingSeconds"] = "Maximum length",
            ["segmentation"] = "Sentence by sentence",
            ["pauseMilliseconds"] = "Pause that ends a sentence",
            ["unloadAfterMinutes"] = "Free memory after",
            ["provider"] = "Compute provider",
            ["threads"] = "Threads",
            ["insertion"] = "Text insertion",
            ["feedback"] = "Circle and tone",
            ["feedbackColor"] = "Circle color",
            ["feedbackSize"] = "Circle size",
            ["feedbackOpacity"] = "Circle opacity",
            ["feedbackTopMargin"] = "Circle margin",
            ["language"] = "Language",
            ["logEnabled"] = "Dictation log",
        },

        KeyNames = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["Ctrl"] = "Ctrl",
            ["LeftCtrl"] = "Left Ctrl",
            ["RightCtrl"] = "Right Ctrl",
            ["Alt"] = "Alt",
            ["LeftAlt"] = "Left Alt",
            ["RightAlt"] = "Right Alt",
            ["Shift"] = "Shift",
            ["LeftShift"] = "Left Shift",
            ["RightShift"] = "Right Shift",
            ["Win"] = "Windows",
            ["LeftWin"] = "Left Windows",
            ["RightWin"] = "Right Windows",
            ["CapsLock"] = "Caps Lock",
            ["Space"] = "Space",
        },

        Percent = value => $"{value}%",
        ThreadCount = value => value == 1 ? "1 thread" : $"{value} threads",
        Never = "Never",
        Off = "Off",

        CaveatAltGr = "Probably AltGr: the characters it types won't work while HexWin runs.",
        CaveatSpace = "Space alone will no longer type spaces while HexWin runs.",
        CaveatBothShifts = "No Shift key will type capitals any more.",
        CaveatLeftShift = "Use the right Shift for capitals.",
        CaveatRightShift = "Use the left Shift for capitals.",
        CaveatCapsLock = "Caps Lock will no longer lock capitals.",

        WindowTitle = "HexWin settings",
        About = version => $"Version {version}\nLocal dictation: nothing leaves your machine.",
        Save = "Save",
        Cancel = "Cancel",
        NavDictation = "Dictation",
        NavCues = "Cues",
        NavEngine = "Engine",
        NavGeneral = "General",

        PageDictation = "Dictation",
        SectionHotkey = "Hotkey",
        HotkeyTitle = "Dictation hotkey",
        HotkeyHint = "Hold to dictate, release to insert.",
        Change = "Change",
        ChangeHotkeyName = "Change the dictation hotkey",
        CapturePrompt = "Press the keys…",
        CaptureHint = "Hold them, then release. Esc to cancel.",
        Holding = keys => $"{keys}…",
        CaptureRefused = "Not allowed. Use Shift, Ctrl, Alt, Windows, Caps Lock, Space or F13–F24.",
        SectionRecording = "Recording",
        MinimumLengthTitle = "Minimum length",
        MinimumLengthHint = "Shorter presses are ignored.",
        MaximumLengthTitle = "Maximum length",
        MaximumLengthHint = "Recording stops beyond this.",
        SectionInsertion = "Insertion",
        InsertionTitle = "Text insertion",
        InsertionHint = "Paste is instant; Type works everywhere.",
        InsertPaste = "Paste",
        InsertType = "Type",
        SegmentationTitle = "Sentence by sentence",
        SegmentationHint = "Inserted at each pause, before you release.",
        PauseTitle = "Pause that ends a sentence",
        PauseHint = "Shorter: sooner, but may split a sentence.",

        PageCues = "Visual and sound cues",
        SectionWhileDictating = "While dictating",
        CircleTitle = "On-screen circle",
        CircleHint = "Red while recording, orange while transcribing.",
        ToneTitle = "Tone at start and end",
        ToneHint = "A short beep as the microphone opens and closes.",
        SectionCircle = "Circle appearance",
        ColorTitle = "Color",
        ColorHint = "Follow the state, or a single color.",
        ColorByState = "By state",
        ColorFixed = "Fixed",
        PickColorName = "Choose the circle color",
        SizeTitle = "Size",
        OpacityTitle = "Opacity",
        TopMarginTitle = "Top margin",

        PageEngine = "Engine",
        EngineNote = "These settings take effect the next time HexWin starts.",
        SectionModel = "Model",
        ModelTitle = "Model folder",
        Browse = "Browse…",
        BrowseModelName = "Choose the model folder",
        ModelNotFound = path => $"Not found: {path}",
        ModelFolderDialog = "Parakeet model folder",
        ModelUnusable = reason => $"This folder does not hold a usable model.\n\n{reason}",
        SectionPerformance = "Performance",
        ThreadsTitle = "Threads",
        ThreadsHint = "Beyond a few, the gain collapses.",
        UnloadTitle = "Free memory after",
        UnloadHint = "The model takes about 1 GB.",

        PageGeneral = "General",
        SectionStartup = "Startup",
        AutoStartTitle = "Start with Windows",
        AutoStartHint = "HexWin sits in the notification area.",
        DesktopShortcutTitle = "Desktop shortcut",
        DesktopShortcutHint = "Starts HexWin, or reopens this window.",
        SectionDisplay = "Display",
        LanguageTitle = "Language",
        LanguageHint = "Not the dictation language.",
        LanguageAuto = "Auto",
        SectionDiagnostics = "Diagnostics",
        LogTitle = "Dictation log",
        LogHint = "Length, level, characters. From the next start.",
        OpenTitle = "Open",
        OpenHint = "For advanced settings or diagnostics.",
        Logs = "Logs",

        NotPersisted = names =>
            $"Applied, but settings.json could not be updated for: {names}.\n"
            + "The file may be open elsewhere or read-only; "
            + "these settings will be lost at the next start.",
        AwaitingRestart = names => $"Saved. Takes effect the next time HexWin starts: {names}.",

        MenuSettings = "Settings…",
        MenuOpenSettingsFile = "Open settings.json",
        MenuOpenLogFolder = "Open log folder",
        MenuShowCircle = "Show the circle while dictating",
        MenuPlayTone = "Play a tone at start and end",
        MenuStartWithWindows = "Start with Windows",
        MenuQuit = "Exit",

        TipLoading = "HexWin — loading the model...",
        TipReady = hotkey => $"HexWin — ready ({hotkey})",
        TipRecording = "HexWin — recording",
        TipTranscribing = "HexWin — transcribing...",
        TipModelMissing = "HexWin — model not found",

        BalloonModelMissing = "Model not found",
        BalloonModelMissingBody = reason => $"{reason}\n\nRun scripts/get-model.ps1.",
        BalloonMicrophone = "Microphone unavailable",
        MicrophoneMissing = "No microphone found. Check that an input device is plugged in "
            + "and allowed in Settings > Privacy & security > Microphone.",
        BalloonCannotOpen = "Cannot open",
        BalloonShortcutFailed = "Couldn't create shortcut",
        BalloonShortcutFailedBody = "The shortcut could not be created on the desktop.",
        DesktopShortcutQuestion = "Add a HexWin shortcut to the desktop?\n\n"
            + "It starts HexWin, or opens its settings when HexWin is already running. "
            + "You can remove it in Settings, General page.",
        DesktopShortcutDescription = "HexWin — local voice dictation. Opens the settings when HexWin is already running.",

        StartupModelMissing = path => $"Model not found: {path}\n\nRun scripts/get-model.ps1 to download it.",
        ModelFileMissing = path => $"Model file missing: {path}.",
        Crashed = (reason, log) => $"HexWin stopped on an error:\n\n{reason}\n\nDetails in {log}",
        CrashLogUnavailable = "(log unavailable)",
    };
}
